CREATE ROLE form_ai_app WITH
LOGIN
PASSWORD 'form_ai_app123'
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOREPLICATION;

ALTER DATABASE form_ai OWNER TO form_ai_app;

GRANT ALL PRIVILEGES ON DATABASE form_ai TO form_ai_app;

\c form_ai;

ALTER SCHEMA public OWNER TO form_ai_app;

GRANT ALL ON SCHEMA public TO form_ai_app;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO form_ai_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO form_ai_app;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO form_ai_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO form_ai_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO form_ai_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO form_ai_app;