#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -v app_db_password="$APP_DB_PASSWORD" <<-'EOSQL'
CREATE ROLE form_ai_app WITH
LOGIN
PASSWORD :'app_db_password'
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOREPLICATION;

ALTER DATABASE form_ai OWNER TO form_ai_app;

GRANT ALL PRIVILEGES ON DATABASE form_ai TO form_ai_app;

\c form_ai

ALTER SCHEMA public OWNER TO form_ai_app;

GRANT ALL ON SCHEMA public TO form_ai_app;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO form_ai_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO form_ai_app;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO form_ai_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO form_ai_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO form_ai_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO form_ai_app;
EOSQL
